#-------------------------------
# General Site Settings
title: Heera,Lee
logo: logo.png # You can add own logo.
description: Web Developer & Designer Portfolio Site.


#-------------------------------
# Author Settings
author:
  name: Heera Lee
  image: crackerie_x-mas.jpg
  say-hello: Hello, I’m <strong>Heera, Lee</strong>
  bio:  <i class="fa-solid fa-laptop-code"></i> Development, Design, Marketing about <strong>web</strong>.<br/>
        <i class="fa-regular fa-face-kiss-wink-heart"></i> Loves watch Cinema & Musical <br/> 
        <i class="fa-solid fa-candy-cane"></i> Merry Crackerie-mas !


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
 github: https://github.com/he22ra
 notion: https://bit.ly/3BNm48B


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-4T6YW201L4 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
